Ignoring exception in command ping
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 848, in process_commands
    yield from command.invoke(ctx)
  File "/home/user/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 362, in invoke
    yield from self.prepare(ctx)
  File "/home/user/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 340, in prepare
    yield from self._parse_arguments(ctx)
  File "/home/user/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 299, in _parse_arguments
    transformed = yield from self.transform(ctx, param)
  File "/home/user/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 207, in transform
    raise MissingRequiredArgument('{0.name} is a required argument that is missing.'.format(param))
discord.ext.commands.errors.MissingRequiredArgument: ctx is a required argument that is missing.
